### ISSUE TITLE
--merge and Cannot enlarge memory arrays

### ISSUE THREAD

**Issue by saczysmark** [breizoreol/memanki#2]
Hi, 
I do like your script. But very often I received the error when I want to merge the course. E.g. I fetched and merge the course https://www.memrise.com/course/1319098/angielski-4/ without any problems, but when I try to do the same with the course https://www.memrise.com/course/1319101/angielski-7/ (command: memanki --merge --id 1319101) I receive the error:

Cannot enlarge memory arrays. Either (1) compile with  -s TOTAL_MEMORY=X  with X higher than the current value 16777216, (2) compile with  -s ALLOW_MEMORY_GROWTH=1  which adjusts the size at runtime but prevents some optimizations, (3) set Module.TOTAL_MEMORY to a higher value before the program runs, or if you want malloc to return NULL (0) instead of this abort, compile with  -s ABORTING_MALLOC=0 
(node:2502) UnhandledPromiseRejectionWarning: abort("Cannot enlarge memory arrays. Either (1) compile with  -s TOTAL_MEMORY=X  with X higher than the current value 16777216, (2) compile with  -s ALLOW_MEMORY_GROWTH=1  which adjusts the size at runtime but prevents some optimizations, (3) set Module.TOTAL_MEMORY to a higher value before the program runs, or if you want malloc to return NULL (0) instead of this abort, compile with  -s ABORTING_MALLOC=0 ") at Error
    at Ra (/usr/local/lib/node_modules/memanki-cli/node_modules/sql.js/js/sql.js:32:124)
    at Qa (/usr/local/lib/node_modules/memanki-cli/node_modules/sql.js/js/sql.js:32:22)
    at p (/usr/local/lib/node_modules/memanki-cli/node_modules/sql.js/js/sql.js:488:103)
    at Function.ba [as Gb] (/usr/local/lib/node_modules/memanki-cli/node_modules/sql.js/js/sql.js:12:164)
    at Ia (/usr/local/lib/node_modules/memanki-cli/node_modules/sql.js/js/sql.js:397:297)
    at _Q (/usr/local/lib/node_modules/memanki-cli/node_modules/sql.js/js/sql.js:465:135615)
    at Iu (/usr/local/lib/node_modules/memanki-cli/node_modules/sql.js/js/sql.js:468:26931)
    at sO (/usr/local/lib/node_modules/memanki-cli/node_modules/sql.js/js/sql.js:465:55965)
    at _f (/usr/local/lib/node_modules/memanki-cli/node_modules/sql.js/js/sql.js:459:91456)
    at Gu (/usr/local/lib/node_modules/memanki-cli/node_modules/sql.js/js/sql.js:468:26226)
    at Fu (/usr/local/lib/node_modules/memanki-cli/node_modules/sql.js/js/sql.js:468:24948)
    at Cu (/usr/local/lib/node_modules/memanki-cli/node_modules/sql.js/js/sql.js:468:23165)
    at Bu (/usr/local/lib/node_modules/memanki-cli/node_modules/sql.js/js/sql.js:468:21949)
    at qu (/usr/local/lib/node_modules/memanki-cli/node_modules/sql.js/js/sql.js:468:16949)
    at cs (/usr/local/lib/node_modules/memanki-cli/node_modules/sql.js/js/sql.js:462:94725)
    at sg (/usr/local/lib/node_modules/memanki-cli/node_modules/sql.js/js/sql.js:459:113005)
If this abort() is unexpected, build with -s ASSERTIONS=1 which can give more information.
(node:2502) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:2502) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

Is this problem on my side or this problem is global?

**Comment by matthieu-rolland** [comment]
THank you for your feedback, unfortunately I've been very busy lately and didn't take care of my open source projects so much, sorry about that.

I will investigate this when I have some time, probably this weekend.

**Comment by matthieu-rolland** [comment]
Ok, it should work fine now, just update your memanki package to version 1.0.3

npm update -g memanki-cli
